version: "2"
neptune-pipeline:
  source:
    neptune:
      port: 8182
      region: "us-east-1"
      iamAuth: true
      aws:
        sts_role_arn: "arn:aws:iam::160718075058:role/OSPipelineRole"
      s3_bucket: "melzarei-data-prepper"
      s3_region: "us-east-1"
#      host: "localhost" # Set up SSH tunnel to remote Neptune cluster
      host: "db-neptune-1.cluster-cilnxdzyusie.us-east-1.neptune.amazonaws.com"
      trust_store_file_path: "config/InternalAndExternalAndAWSTrustStore.jks"
      # trust_store_password: "amazon"
      acknowledgments: false
      export: false
      stream: true
      streamType: "propertygraph"
  processor:
    - aggregate:
        identification_keys: [ "entity_id", "document_type" ]
        group_duration: "15s"
        action:
          put_all:
  sink:
    - opensearch:
        hosts:
          [
            "https://search-testdomain2-vlb5qyr5jsv4ozhbvkmi24jzva.aos.us-east-1.on.aws"
          ]
        index: "neptune"
        index_type: custom
        document_id: "${/entity_id}"
        action: "scripted_update"
        scripts:
          update_script: config/update_script.painless
        aws:
          sts_role_arn: "arn:aws:iam::160718075058:role/OSPipelineRole"
          region: "us-east-1"